[package]
name = "fusarium"
version = "0.1.0"
edition = "2018"
authors = ["Gatlin Newhouse"]
description = "Fusarium, named after the fungi that affects corn (and its kernels), is an OS Kernel"
readme = "./README.md"

[dependencies]
bootloader = { version = "0.9", features = ["map_physical_memory"] }
volatile = { version = "0.2.6" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = { version = "0.9.8" }
x86_64 = { version = "0.14.2" }
uart_16550 = { version = "0.2.0" }
pic8259 = { version = "0.10.1", optional = true }
pc-keyboard = { version = "0.7.0" }
linked_list_allocator = { version = "0.9.0", optional = true }

[features]
default = ["pic8259", "alloc-my-free-list"]
pic8259 = ["dep:pic8259"]
x86 = []
arm = []
alloc-linked-list = ["dep:linked_list_allocator"]
alloc-bump = []
alloc-my-free-list = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
test-args = [
  "-device",
  "isa-debug-exit,iobase=0xf4,iosize=0x04",
  "-serial",
  "stdio",
  "-display",
  "none",
]
test-success-exit-code = 33
test-timeout = 300

[[test]]
name = "address_translation"
harness = false

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "doublefault"
harness = false

[[test]]
name = "pagefault"
harness = false

[[test]]
name = "stack_overflow"
harness = false
