[package]
name = "fusarium"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = { version = "0.9" }
volatile = { version = "0.2.6" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = { version = "0.5.2" }
x86_64 = { version = "0.14.2" }
uart_16550 = { version = "0.2.0" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
test-args = [
  "-device",
  "isa-debug-exit,iobase=0xf4,iosize=0x04",
  "-serial",
  "stdio",
  "-display",
  "none",
]
test-success-exit-code = 33
test-timeout = 300

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "doublefault"
harness = false

[[test]]
name = "stack_overflow"
harness = false
