[build]
#target = "x86_64-fusarium.json"
target = "armv6a-fusarium.json"

[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true

[target.x86_64-fusarium] # aka QEMU
runner = "bootimage runner"

[target.armv6a-fusarium] # aka Pi Zero W
rustflags = ["-C", "link-arg=-Tlink.x"]
runner = "qemu-system-arm -M raspi0 -kernel "
