[build]
target = "x86_64-fusarium.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["alloc", "core", "compiler_builtins"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
